#ifndef SDSPI_HAL_H
#define SDSPI_HAL_H

#include "sdspi_regs.h"

//BoxLambda Board Definitions for SDSPI SW, derived from
//https://github.com/ZipCPU/zbasic/blob/master/sw/zlib/board.h

#define _BOARD_HAS_SDSPI

#define	SDSPI_SETAUX	0x0000ff
#define	SDSPI_READAUX	0x0000bf
#define	SDSPI_CMD		0x000040
#define	SDSPI_ACMD		(0x040+55) // CMD55
#define	SDSPI_FIFO_OP	(SDSPI_CMD_F_MASK)	// Read only
#define	SDSPI_WRITEOP	(SDSPI_CMD_WR_MASK|SDSPI_CMD_F_MASK)	// Write to the FIFO
#define	SDSPI_ALTFIFO	SDSPI_CMD_SEL_MASK
#define	SDSPI_BUSY		SDSPI_CMD_BUSY_MASK
#define	SDSPI_ERROR		SDSPI_CMD_ERR_MASK
#define	SDSPI_CLEARERR	SDSPI_CMD_ERR_MASK
// #define	SDSPI_CRCERR	0x010000
// #define	SDSPI_ERRTOK	0x020000
#define	SDSPI_REMOVED	SDSPI_CMD_REM_MASK
#define	SDSPI_PRESENTN	SDSPI_CMD_P_MASK
#define	SDSPI_RESET		0x100000	// Read only
#define	SDSPI_WATCHDOG	0x200000	// Read only
#define	SDSPI_GO_IDLE	((SDSPI_REMOVED|SDSPI_CLEARERR|SDSPI_CMD)+0)
#define	SDSPI_READ_SECTOR	((SDSPI_CMD|SDSPI_CLEARERR|SDSPI_FIFO_OP)+17)
#define	SDSPI_WRITE_SECTOR	((SDSPI_CMD|SDSPI_CLEARERR|SDSPI_WRITEOP)+24)
#define SDSPI_READREG  (SDSPI_CMD_ERESP_R2_R3_R7<<SDSPI_CMD_ERESP_LSB)

#define  SDSPI_WAIT_WHILE_BUSY  { int r; do { r = SDSPI->CMD; if (r & (SDSPI_ERROR|SDSPI_PRESENTN)) break; } while(r & SDSPI_BUSY); }


#define SDSPI_BIG_ENDIAN 0
#define SDSPI_LITTLE_ENDIAN 1

#define SDSPI_IP_ENDIANNESS SDSPI_LITTLE_ENDIAN

#if (!(defined SDSPI_CPU_IS_BIG_ENDIAN) && !(defined SDSPI_CPU_IS_LITTLE_ENDIAN))
#error "CPU endianness not set: define SDSPI_CPU_IS_BIG_ENDIAN or SDSPI_CPU_IS_LITTLE_ENDIAN"
#endif /*SDSPI_CPU_ENDIANNESS*/

#ifdef SDSPI_CPU_IS_BIG_ENDIAN
#define SDSPI_CPU_ENDIANNESS SDSPI_BIG_ENDIAN
#else
#define SDSPI_CPU_ENDIANNESS SDSPI_LITTLE_ENDIAN
#endif

#if (SDSPI_CPU_ENDIANNESS == SDSPI_IP_ENDIANNESS)
#define ENDIAN_CAST_uint32_t(w) (w)
#else
#define ENDIAN_CAST_uint32_t(w) (((w&0x000000ff)<<24) | ((w&0x0000ff00)<<8) | ((w&0x00ff0000)>>8) | ((w&0xff000000)>>24))
#endif

#endif //SDSPI_HAL_H
