\ --- I2C_MASTER
\ --- 32-bit register bitfield accessors

$10000200 constant I2C_MASTER_BASE_ADDR


\ CMD - I2C master command register
I2C_MASTER_BASE_ADDR $0 + constant I2C_MASTER_CMD_ADDR

\ -- Address Mask Offset
I2C_MASTER_CMD_ADDR $ff #0 bitfield@ I2C_MASTER_CMD_NUM_BYTES@
I2C_MASTER_CMD_ADDR $ff #0 bitfield! I2C_MASTER_CMD_NUM_BYTES!
I2C_MASTER_CMD_ADDR $ff00 #8 bitfield@ I2C_MASTER_CMD_START_ADDR@
I2C_MASTER_CMD_ADDR $ff00 #8 bitfield! I2C_MASTER_CMD_START_ADDR!
I2C_MASTER_CMD_ADDR $10000 #16 bitfield@ I2C_MASTER_CMD_RD_N_WR@
I2C_MASTER_CMD_ADDR $10000 #16 bitfield! I2C_MASTER_CMD_RD_N_WR!
I2C_MASTER_CMD_ADDR $fe0000 #17 bitfield@ I2C_MASTER_CMD_SLAVE_ADDR@
I2C_MASTER_CMD_ADDR $fe0000 #17 bitfield! I2C_MASTER_CMD_SLAVE_ADDR!
I2C_MASTER_CMD_ADDR $40000000 #30 bitfield@ I2C_MASTER_CMD_ERR@
I2C_MASTER_CMD_ADDR $80000000 #31 bitfield@ I2C_MASTER_CMD_BUSY@

\ SPD - Speed register
I2C_MASTER_BASE_ADDR $4 + constant I2C_MASTER_SPD_ADDR

\ -- Address Mask Offset
I2C_MASTER_SPD_ADDR $fffff #0 bitfield@ I2C_MASTER_SPD_VALUE@
I2C_MASTER_SPD_ADDR $fffff #0 bitfield! I2C_MASTER_SPD_VALUE!

\ ISR - Interrupt Status Register
I2C_MASTER_BASE_ADDR $8 + constant I2C_MASTER_ISR_ADDR

\ -- Address Mask Offset
I2C_MASTER_ISR_ADDR $1 #0 bitfield@ I2C_MASTER_ISR_BUSY@
I2C_MASTER_ISR_ADDR $1 #0 bitfield! I2C_MASTER_ISR_BUSY!

\ IEN - Interrupt Enable Register
I2C_MASTER_BASE_ADDR $c + constant I2C_MASTER_IEN_ADDR

\ -- Address Mask Offset
I2C_MASTER_IEN_ADDR $1 #0 bitfield@ I2C_MASTER_IEN_BUSY@
I2C_MASTER_IEN_ADDR $1 #0 bitfield! I2C_MASTER_IEN_BUSY!
