#Path to the root of the repository
TOP_DIR := ../..
TOP_MODULE := wb_gpio_wrapper

#Flag indicating Out-of-Context Synthesis.
#The value corresponds the Bender.yml target used to select OOC specific files and defines.
OOC = wb_gpio

#Include common Make flags and rules
include $(TOP_DIR)/build_sys/common.mk
