#Path to the root of the repository
TOP_DIR := ../..
TOP_MODULE := wb_wbuart_wrap_wrap

#Flag indicating Out-of-Context Synthesis.
#The value corresponds the Bender.yml target used to select OOC specific files and defines.
OOC = wbuart32

#Include common Make flags and rules
include $(TOP_DIR)/build_sys/common.mk

