#TCL script interfacing the build system with Vivado
VIVADO_TCL := $(TOP_DIR)/build_sys/vivado.tcl
#Currently Arty A7-35T only
PART = xc7a35ticsg324-1L
#The HDL sources script generated by Bender goes here
BENDER_GEN_SCRIPT = generated/sources.tcl

#List of memory files referenced in the Bender package manifest
MEM_FILES := $(shell bender update && bender script flist -t memory)
MEM_FILES_GEN_SCRIPT = generated/mem_files.tcl
#List of .xdc constraint files referenced in the Bender package manifest
CONSTRAINTS := $(shell bender update && bender script flist -n -t constraints)
CONSTRAINTS_GEN_SCRIPT = generated/constraints.tcl

default: dryrun

#Whenever a bender package manifest has changed, bender update needs to be run.
.PHONY: bender_update
bender_update:
	bender update

#Rule to generate TCL 'sub' script that adds constraint files to the project
.PHONY: constraints
constraints: $(CONSTRAINTS)
	mkdir -p generated
	$(RM) -f $(CONSTRAINTS_GEN_SCRIPT)
	$(foreach constraint, $^, echo add_files -fileset constrs_1 $(constraint) >> $(CONSTRAINTS_GEN_SCRIPT))
ifdef OOC
	$(foreach constraint, $^, echo set_property USED_IN {synthesis out_of_context} [get_files $(constraint)] >> $(CONSTRAINTS_GEN_SCRIPT))
endif

#Rule to generate TCL 'sub' script that adds memory files to the project
.PHONY: mem_files
mem_files:
	mkdir -p generated
	$(RM) -f $(MEM_FILES_GEN_SCRIPT)
	$(foreach mem_file, $(MEM_FILES), echo add_files -norecurse $(mem_file) >> $(MEM_FILES_GEN_SCRIPT))

.PHONY: force
force :

#Pattern rule for memory files: Go to the memory file's directory and run Make there.
%.mem : force
	$(MAKE) -C $(@D)

#Rule to generate TCL 'sub' script that adds HDL source files to the project
$(BENDER_GEN_SCRIPT): bender_update
	mkdir -p generated
ifdef OOC
	bender script -t synthesis -t ooc vivado > $(BENDER_GEN_SCRIPT)
else
	bender script -t synthesis vivado > $(BENDER_GEN_SCRIPT)
endif

#dryrun just creates the vivado project, but doesn't kick-off synthesis or implementation.
#synth generates the project and synthesizes it.
#imple generates the project, synthesizes it and implements it.
.PHONY: synth dryrun
dryrun synth impl: $(BENDER_GEN_SCRIPT) mem_files constraints
	vivado -nolog -nojournal -mode batch -source $(VIVADO_TCL) \
	-tclargs -project generated/project -cmd $@ -part $(PART) \
	-sources $(BENDER_GEN_SCRIPT) -constraints $(CONSTRAINTS_GEN_SCRIPT) \
	-mem_files $(MEM_FILES_GEN_SCRIPT) -outputDir generated

.PHONY: clean
clean:
	$(RM) *.log
	$(RM) -rf generated
