'start
(vera :display :enable)
(vera :sprites :enable)
(defvar w 64)
(defvar h 64)
(defvar bpp 8)
(vera :tileset 0 :init :width w :height h :bpp bpp :num_tiles 8)
(vera :tileset 0 :info)

(vera :sprite 200 :init)
(vera :sprite 1 :init)
(vera :sprite 200 :tileset 0 :tile_idx 2)
(vera :sprite 1 :tileset 400 :tile_idx 2)
(vera :sprite 1 :tileset 40 :tile_idx 2)
(vera :sprite 1 :tileset 0 :tile_idx 200)
(vera :sprite 1 :tileset 0 :tile_idx 2)
(vera :sprite 200 :z 0)
(vera :sprite 1 :z 20)
(vera :sprite 1 :z VERA_SPRITE_Z_BG_L0)
(vera :sprite 1000 :pal_offset 1)
(vera :sprite 1 :pal_offset 1000)
(vera :sprite 1 :pal_offset 1)
(vera :sprite 1000 :hflip :enable)
(vera :sprite 1 :hflip :enable)
(vera :sprite 1000 :vflip :enable)
(vera :sprite 1 :vflip :enable)
(vera :sprite 1000 :mask 1)
(vera :sprite 1 :mask 1)

'end
