'start
(vera_display_enable 1)
(vera_tileset 0 16 16 8 32)
(dotimes (ii 16)
  (dotimes (jj (1+ ii))
    (vera_tileset_pixel 0 1 jj ii VERA_COLOR_BLUE)))
(vera_map 0 32 32 VERA_MAP_TYPE_TILE)
(vera_layer_map 0 0)
(vera_layer_tileset 0 0)
(defvar row1 10)
(defvar col1 20)
(defvar row2 20)
(defvar col2 10)
(defvar row3 16)
(defvar col3 16)
(vera_map_entry 0 col1 row1 1)
(vera_map_entry 0 col2 row2 (logior VERA_MAPENTRY_HFLIP_MASK VERA_MAPENTRY_VFLIP_MASK 1))
(vera_map_entry 0 col3 row3 (logior (ash 1 VERA_MAPENTRY_PAL_OFFSET_SHIFT) 1))
(vera_layer_enable 0 1)
(vera_irqline 0)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(dolist (rowcol (list (cons row1 col1) (cons row2 col2) (cons row3 col3)))
  (vera_irqline (* 16 (car rowcol)))
  (vera_line_capture_enable 1)
  (loop (if (= (vera_line_capture_enable) 0) (return)))
  (dotimes (ii 16)
    (print (vera_line_capture_read_pixel (+ (* 16 (cdr rowcol)) ii)))))
'end
