'start
(vera_display_enable 1)
(vera_sprite_enable 1)
(defvar w 8)
(defvar h 8)
(defvar bpp 8)
(vera_tileset 0 w h bpp 8)
(vera_tileset 0)
(vera_sprite_init 1)
(vera_sprite_init 65)
(vera_sprite_tile 1 0 1)
(vera_sprite_tile 65 0 1)
(vera_sprite_pal_offset 65 1)
(vera_sprite_z_depth 1 VERA_SPRITE_Z_L1)
(vera_sprite_z_depth 65 VERA_SPRITE_Z_L1)
(vera_sprite_pixel 1 0 0 VERA_COLOR_CYAN)
(vera_sprite_x 1 40)
(vera_sprite_y 1 50)
(vera_sprite_x 65 100)
(vera_sprite_y 65 200)
(vera_irqline 50)
(vera_spritebank 0)
(vera_spritebank)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(print (vera_line_capture_read_pixel 40))
(vera_irqline 200)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(print (vera_line_capture_read_pixel 100))
(vera_irqline 50)
(vera_spritebank 1)
(vera_spritebank)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(print (vera_line_capture_read_pixel 40))
(vera_irqline 200)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(print (vera_line_capture_read_pixel 100))
'end
