'start
(vera_display_enable 1)
(vera_sprite_enable 1)
(defvar w 64)
(defvar h 64)
(defvar bpp 8)
(vera_tileset 0 w h bpp 8)
(vera_tileset 0)
(vera_sprite_init 1)
(vera_sprite_tile 1 0 2)
(vera_sprite_z_depth 1 VERA_SPRITE_Z_L1)
(vera_sprite_pixel 1 00 64 VERA_COLOR_CYAN)
(vera_sprite_pixel 1 64 00 VERA_COLOR_CYAN)
(vera_tileset_deinit 0)
(setq w 32)
(setq h 32)
(vera_tileset 0 w h bpp 8)
(vera_tileset 0)
(vera_sprite_init 1)
(vera_sprite_tile 1 0 2)
(vera_sprite_z_depth 1 VERA_SPRITE_Z_L1)
(vera_sprite_pixel 1 00 32 VERA_COLOR_CYAN)
(vera_sprite_pixel 1 32 00 VERA_COLOR_CYAN)
(vera_tileset_deinit 0)
'end
