'start
(vera_display_enable 1)
(vera_layer_enable 0 1)
(vera_map 0 32 32 VERA_MAP_TYPE_TILE)
(vera_tileset 0 16 16 8 32)
(vera_layer_map 0 0)
(vera_layer_tileset 0 0)
(vera_map_entry 0 0 0 1)
(dotimes (ii 16)
  (vera_tileset_pixel 0 1 ii ii VERA_COLOR_WHITE)
  (vera_tileset_pixel 0 1 (- 15 ii) ii VERA_COLOR_WHITE))
(vera_irqline 15)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(vera_line_capture_read_pixel 14)
(vera_line_capture_read_pixel 15)
(vera_line_capture_read_pixel 16)
(vera_hscale 0.5)
(vera_vscale 0.5)
(vera_hscale)
(vera_vscale)
(vera_irqline 31)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(vera_line_capture_read_pixel 29)
(vera_line_capture_read_pixel 30)
(vera_line_capture_read_pixel 31)
(vera_line_capture_read_pixel 32)
'end
