'start
(vera :display :enable)
(vera :sprites :enable)
(vera :map 0 :init :width 32 :height 32 :map_type VERA_MAP_TYPE_TILE)
(vera :map 1 :init :width 32 :height 32 :map_type VERA_MAP_TYPE_TILE)
(vera :layer 0 :map 0)
(vera :layer 1 :map 1)
(vera :map 0 :entry :x 0 :y 0 :val #x0002)
(vera :map 1 :entry :x 0 :y 0 :val #x2002)

(defvar w 8)
(defvar h 8)
(defvar bpp 8)
(vera :tileset 1 :init :width w :height h :bpp bpp :num_tiles 8)
(vera :layer 0 :tileset 1)
(vera :layer 1 :tileset 1)
(vera :sprite 1 :init)
(vera :sprite 1 :tileset 1 :tile 2)
(vera :sprite 1 :tileset)
(vera :sprite 1 :z VERA_SPRITE_Z_DIS)
(vera :sprite 1 :z)
(vera :sprite 1 :pal_offset 1)
(dotimes (yy h)
  (dotimes (xx (min w (1+ yy)))
    (vera_tileset_pixel 1 2 xx yy VERA_COLOR_CYAN)))



(vera :irqline 0)
(vera :linecapture :enable)
(loop (if (= (vera :linecapture :enabled) 0) (return)))
(print (vera :linecapture :pixel :x 0))

(vera :sprite 1 :z VERA_SPRITE_Z_BG_L0)
(vera :sprite 1 :z)
(vera :linecapture :enable)
(loop (if (= (vera :linecapture :enabled) 0) (return)))
(print (vera :linecapture :pixel :x 0))

(vera :layer 0 :enable)
(vera :linecapture :enable)
(loop (if (= (vera :linecapture :enabled) 0) (return)))
(print (vera :linecapture :pixel :x 0))
(vera :sprite 1 :z VERA_SPRITE_Z_L0_L1)
(vera :sprite 1 :z)
(vera :linecapture :enable)
(loop (if (= (vera :linecapture :enabled) 0) (return)))
(print (vera :linecapture :pixel :x 0))
(vera :layer 1 :enable)
(vera :linecapture :enable)
(loop (if (= (vera :linecapture :enabled) 0) (return)))
(print (vera :linecapture :pixel :x 0))
(vera :sprite 1 :z VERA_SPRITE_Z_L1)
(vera :sprite 1 :z)
(vera :linecapture :enable)
(loop (if (= (vera :linecapture :enabled) 0) (return)))
(print (vera :linecapture :pixel :x 0))

'end
