'start
(vera_display_enable 1)
(vera_tileset 0 16 16 1 32)
(dotimes (ii 16)
  (vera_tileset_pixel 0 1 ii ii 1)
  (vera_tileset_pixel 0 1 (- 15 ii) ii 1))
(vera_layer_tileset 0 0)
(dolist (cols (list 32 64 128))
  (dolist (rows (list 32 64 128))
    (vera_map 0 cols rows VERA_MAP_TYPE_TXT16)
    (vera_layer_map 0 0)
    (vera_map_entry 0 0 0
                    (logior (ash VERA_COLOR_GREEN 12) (ash VERA_COLOR_WHITE 8) 1))
    (vera_map_entry 0 (1- cols) 0
                    (logior (ash VERA_COLOR_BLUE 12) (ash VERA_COLOR_WHITE 8) 1))
    (vera_map_entry 0 0 (1- rows)
                    (logior (ash VERA_COLOR_PURPLE 12) (ash VERA_COLOR_YELLOW 8) 1))
    (vera_map_entry 0 (1- cols) (1- rows)
                    (logior (ash VERA_COLOR_GREEN 12) (ash VERA_COLOR_GREY 8) 1))
    (format t "~x~%"  (vera_map_entry 0 0 0))
    (format t "~x~%" (vera_map_entry 0 (1- cols) 0))
    (format t "~x~%" (vera_map_entry 0 0 (1- rows)))
    (format t "~x~%" (vera_map_entry 0 (1- cols) (1- rows)))
    (vera_map_deinit 0)))
'end
