'start
(vera_display_enable 1)
(vera_layer_enable 0)
(vera_layer_enable 1)
(vera_map 0 32 32 VERA_MAP_TYPE_TILE)
(vera_map 1 32 32 VERA_MAP_TYPE_TILE)
(vera_tileset 0 16 16 8 32)
(vera_layer_map 0 0)
(vera_layer_map 1 1)
(vera_layer_tileset 0 0)
(vera_layer_tileset 1 0)
(vera_map_entry 0 1 1 1)
(vera_map_entry 1 1 1 2)
(dotimes (ii 16)
  (vera_tileset_pixel 0 1 0 ii VERA_COLOR_RED))
(dotimes (ii 16)
  (vera_tileset_pixel 0 2 ii 0 VERA_COLOR_BLUE))
(vera_irqline 16)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(vera_line_capture_read_pixel 16)
(vera_layer_enable 0 1)
(vera_layer_enable 0)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(vera_line_capture_read_pixel 16)
(vera_layer_enable 1 1)
(vera_layer_enable 1)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(vera_line_capture_read_pixel 16)
'end
