'start
(vera_display_enable 1)
(vera_sprite_enable 1)
(vera_map 0 32 32 VERA_MAP_TYPE_TILE)
(vera_map 1 32 32 VERA_MAP_TYPE_TILE)
(vera_layer_map 0 0)
(vera_layer_map 1 1)
(vera_map_entry 0 0 0 #x0002)
(vera_map_entry 1 0 0 #x2002)
(defvar w 8)
(defvar h 8)
(defvar bpp 8)
(vera_tileset 1 w h bpp 8)
(vera_layer_tileset 0 1)
(vera_layer_tileset 1 1)
(vera_sprite_init 1)
(vera_sprite_tile 1 1 2)
(vera_sprite_tile 1)
(vera_sprite_z_depth 1 VERA_SPRITE_Z_DIS)
(vera_sprite_z_depth 1)
(vera_sprite_pal_offset 1 1)
(dotimes (yy h)
  (dotimes (xx (min w (1+ yy)))
    (vera_sprite_pixel 1 xx yy VERA_COLOR_CYAN)))



(vera_irqline 0)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(print (vera_line_capture_read_pixel 0))
(vera_sprite_z_depth 1 VERA_SPRITE_Z_BG_L0)
(vera_sprite_z_depth 1)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(print (vera_line_capture_read_pixel 0))
(vera_layer_enable 0 1)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(print (vera_line_capture_read_pixel 0))
(vera_sprite_z_depth 1 VERA_SPRITE_Z_L0_L1)
(vera_sprite_z_depth 1)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(print (vera_line_capture_read_pixel 0))
(vera_layer_enable 1 1)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(print (vera_line_capture_read_pixel 0))
(vera_sprite_z_depth 1 VERA_SPRITE_Z_L1)
(vera_sprite_z_depth 1)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(print (vera_line_capture_read_pixel 0))
'end
