'start
(vera_display_enable 1)
(vera_layer_enable 0 1)
(vera_layer_enable 0)
(vera_map 0 32 32 VERA_MAP_TYPE_TILE)
(vera_tileset 0 16 16 8 32)
(vera_layer_map 0 0)
(vera_layer_tileset 0 0)
(vera_map_entry 0 2 2 1)
(dotimes (ii 16)
  (vera_tileset_pixel 0 1 ii ii VERA_COLOR_WHITE)
  (vera_tileset_pixel 0 1 (- 15 ii) ii VERA_COLOR_WHITE))
(vera_layer_hscroll 0 16)
(vera_layer_vscroll 0 16)
(vera_layer_hscroll)
(vera_layer_vscroll)
(vera_irqline 16)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(dotimes (ii 3) (print (vera_line_capture_read_pixel (+ ii 15))))
(vera_irqline 32)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(dotimes (ii 3) (print (vera_line_capture_read_pixel (+ ii 31))))
'end
