'start
(vera_display_enable 1)
(vera_tileset 0 16 16 1 32)
(dotimes (ii 16)
  (vera_tileset_pixel 0 1 ii ii 1)
  (vera_tileset_pixel 0 1 (- 15 ii) ii 1))
(vera_layer_tileset 0 0)
(let ((cols (list 256 256 256 32 64 128))
      (rows (list 32 64 128 256 256 256)))
  (mapc (lambda (r c)
          (vera_map 0 c r VERA_MAP_TYPE_TXT16)
          (vera_layer_map 0 0)
          (vera_map_entry 0 0 0
                          (logior (ash VERA_COLOR_GREEN 12) (ash VERA_COLOR_WHITE 8) 1))
          (vera_map_entry 0 (1- c) 0
                          (logior (ash VERA_COLOR_BLUE 12) (ash VERA_COLOR_WHITE 8) 1))
          (vera_map_entry 0 0 (1- r)
                          (logior (ash VERA_COLOR_PURPLE 12) (ash VERA_COLOR_YELLOW 8) 1))
          (vera_map_entry 0 (1- c) (1- r)
                          (logior (ash VERA_COLOR_GREEN 12) (ash VERA_COLOR_GREY 8) 1))
          (format t "~x~%"  (vera_map_entry 0 0 0))
          (format t "~x~%" (vera_map_entry 0 (1- c) 0))
          (format t "~x~%" (vera_map_entry 0 0 (1- r)))
          (format t "~x~%" (vera_map_entry 0 (1- c) (1- r)))
          (vera_map_deinit 0))
        rows cols))
'end
