'start
(defvar map_sz 32)
(defvar tile_sz 16)
(defvar sprite_sz 64)
(defvar x 128)
(defvar y 88)
(defvar bpp 4)
(defvar scale 0.5)
(vera_display_enable 1)
(vera_palette 0 8 8 15)
(vera_hscale scale)
(vera_vscale scale)
(vera_sprites_enable 1)
(vera_tileset 0 tile_sz tile_sz bpp 1)
(vera_tileset 1 sprite_sz sprite_sz bpp 1)
(vera_map 0 map_sz map_sz VERA_MAP_TYPE_TILE)
(vera_layer_enable 0 1)
(vera_layer_map 0 0)
(vera_layer_tileset 0 0)
(dotimes (ii map_sz)
  (dotimes (jj map_sz)
  (vera_map_entry 0 ii jj 0)))
(dotimes (ii tile_sz)
  (vera_tileset_pixel 0 0 ii 0 VERA_COLOR_YELLOW)
  (vera_tileset_pixel 0 0 0 ii VERA_COLOR_YELLOW)
  (vera_tileset_pixel 0 0 ii (1- tile_sz) VERA_COLOR_YELLOW)
  (vera_tileset_pixel 0 0 (1- tile_sz) ii VERA_COLOR_YELLOW))
(dotimes (ii sprite_sz)
  (dotimes (jj sprite_sz)
  (vera_tileset_pixel 1 0 ii jj VERA_COLOR_WHITE)))
(vera_sprite_init 0)
(vera_sprite_tile 0 1 0)
(vera_sprite_z_depth 0 VERA_SPRITE_Z_L1)
(vera_sprite_x 0 x)
(vera_sprite_y 0 y)
'end

