'start
(vera_display_enable 1)
(vera_layer_enable 0 1)
(dolist (bpp (list 2 4 8))
  (vera_tileset 0 320 32 bpp 1)
  (print (vera_tileset 0))
  (vera_layer_bitmap 0 0 0)
  (vera_layer_pal_offset 0 0)
  (print (vera_layer_pal_offset 0))
  (vera_tileset_pixel 0 0 0 0 1)
  (vera_irqline 0)
  (vera_line_capture_enable 1)
  (loop (if (= (vera_line_capture_enable) 0) (return)))
  (vera_line_capture_enable 1)
  (loop (if (= (vera_line_capture_enable) 0) (return)))
  (print (vera_line_capture_read_pixel 0))
  (print (vera_palette 1))
  (vera_layer_pal_offset 0 1)
  (print (vera_layer_pal_offset 0))
  (loop (if (= (vera_line_capture_enable) 0) (return)))
  (vera_line_capture_enable 1)
  (loop (if (= (vera_line_capture_enable) 0) (return)))
  (print (vera_line_capture_read_pixel 0))
  (print (vera_palette 17))
  (vera_layer_pal_offset 0 4)
  (print (vera_layer_pal_offset 0))
  (loop (if (= (vera_line_capture_enable) 0) (return)))
  (vera_line_capture_enable 1)
  (loop (if (= (vera_line_capture_enable) 0) (return)))
  (print (vera_line_capture_read_pixel 0))
  (print (vera_palette (1+ (* 4 16))))
  (vera_tileset_deinit 0))
'end
