'start
(vera_display_enable 1)
(vera_layer_enable 0 1)
(vera_bitmap 0 320 32 8)
(vera_layer_bitmap 0 0)
(vera_bitmap_pixel 0 0 0 VERA_COLOR_BLACK)
(vera_bitmap_pixel 0 1 0 VERA_COLOR_WHITE)
(vera_bitmap_pixel 0 2 0 VERA_COLOR_RED)
(vera_bitmap_pixel 0 3 0 VERA_COLOR_CYAN)
(vera_bitmap_pixel 0 4 0 VERA_COLOR_PURPLE)
(vera_bitmap_pixel 0 5 0 VERA_COLOR_GREEN)
(vera_bitmap_pixel 0 6 0 VERA_COLOR_BLUE)
(vera_bitmap_pixel 0 7 0 VERA_COLOR_YELLOW)
(vera_bitmap_pixel 0 8 0 VERA_COLOR_ORANGE)
(vera_bitmap_pixel 0 9 0 VERA_COLOR_BROWN)
(vera_bitmap_pixel 0 10 0 VERA_COLOR_LIGHT_RED)
(vera_bitmap_pixel 0 11 0 VERA_COLOR_DARK_GREY)
(vera_bitmap_pixel 0 12 0 VERA_COLOR_GREY)
(vera_bitmap_pixel 0 13 0 VERA_COLOR_LIGHT_GREEN)
(vera_bitmap_pixel 0 14 0 VERA_COLOR_LIGHT_BLUE)
(vera_bitmap_pixel 0 15 0 VERA_COLOR_LIGHT_GREY)
(vera_bitmap_pixel 0 16 0 VERA_COLOR_GRAYSCALE_0)
(vera_bitmap_pixel 0 17 0 VERA_COLOR_GRAYSCALE_1)
(vera_bitmap_pixel 0 18 0 VERA_COLOR_GRAYSCALE_2)
(vera_bitmap_pixel 0 19 0 VERA_COLOR_GRAYSCALE_3)
(vera_bitmap_pixel 0 20 0 VERA_COLOR_GRAYSCALE_4)
(vera_bitmap_pixel 0 21 0 VERA_COLOR_GRAYSCALE_5)
(vera_bitmap_pixel 0 22 0 VERA_COLOR_GRAYSCALE_6)
(vera_bitmap_pixel 0 23 0 VERA_COLOR_GRAYSCALE_7)
(vera_bitmap_pixel 0 24 0 VERA_COLOR_GRAYSCALE_8)
(vera_bitmap_pixel 0 25 0 VERA_COLOR_GRAYSCALE_9)
(vera_bitmap_pixel 0 26 0 VERA_COLOR_GRAYSCALE_10)
(vera_bitmap_pixel 0 27 0 VERA_COLOR_GRAYSCALE_11)
(vera_bitmap_pixel 0 28 0 VERA_COLOR_GRAYSCALE_12)
(vera_bitmap_pixel 0 29 0 VERA_COLOR_GRAYSCALE_13)
(vera_bitmap_pixel 0 30 0 VERA_COLOR_GRAYSCALE_14)
(vera_bitmap_pixel 0 31 0 VERA_COLOR_GRAYSCALE_15)
(vera_irqline 0)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(dotimes (ii 32)
  (let ((rgb (vera_line_capture_read_pixel ii)))
    (mapc (lambda (c) (format t "~x " c)) rgb))
  (format t "~%"))
'end
