'start
(vera :display :enable)
(vera :sprites :enable)
(defvar w 16)
(dolist (h (list 8 16 32 64))
  (dolist (bpp (list 4 8))
    (vera :tileset 0 :width w :height h :bpp bpp :num_tiles 8)
    (vera :tileset 0 :info)
    (vera :sprite 1 :init)
    (vera :sprite 1 :tileset 0 :tile 2)
    (vera :sprite 1 :z VERA_SPRITE_Z_L1)
    (dotimes (yy h)
      (dotimes (xx (min w (1+ yy)))
        (vera_tileset_pixel 0 2 xx yy VERA_COLOR_CYAN)))
    (vera :irqline 0)
    (vera :linecapture :enable)
    (loop (if (= (vera :linecapture :enabled) 0) (return)))
    (print (vera :linecapture :pixel :x 0))
    (print (vera :linecapture :pixel :x 1))
    (vera :irqline (- h 1))
    (vera :linecapture :enable)
    (loop (if (= (vera :linecapture :enabled) 0) (return)))
    (print (vera :linecapture :pixel :x 0))
    (print (vera :linecapture :pixel :x 7))
    (print (vera :linecapture :pixel :x (1- (min w h))))
    (print (vera :linecapture :pixel :x (min w h)))
    (vera :irqline h)
    (vera :linecapture :enable)
    (loop (if (= (vera :linecapture :enabled) 0) (return)))
    (print (vera :linecapture :pixel :x 0))
    (print (vera :linecapture :pixel :x 7))
    (print (vera :linecapture :pixel :x (1- (min w h))))
    (print (vera :linecapture :pixel :x (min w h)))
    (dotimes (yy h)
      (dotimes (xx (min w (1+ yy)))
        (vera_tileset_pixel 0 2 xx yy 0)))
    (vera :tileset 0 :deinit)))

<wait 20>
'end
