'start
(vera_display_enable 1)
(vera_layer_enable 0 1)
(vera_tileset 0 320 32 8 1)
(vera_layer_bitmap 0 0 0)
(vera_tileset_pixel 0 0 0 0 255)
(print (vera_tileset_pixel 0 0 0 0))
(vera_irqline 0)
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(print (vera_line_capture_read_pixel 0))
(print (vera_line_capture_read_pixel 1))
(vera_palette 0 3 2 1)
(vera_palette 255 1 2 3)
(print (vera_palette 0))
(print (vera_palette 255))
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(print (vera_line_capture_read_pixel 0))
(print (vera_line_capture_read_pixel 1))
(vera_palette)
(print (vera_palette 0))
(print (vera_palette 255))
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(vera_line_capture_enable 1)
(loop (if (= (vera_line_capture_enable) 0) (return)))
(print (vera_line_capture_read_pixel 0))
(print (vera_line_capture_read_pixel 1))
'end
