'start
(vera :display :enable)
(vera :layer 0 :enable)
(dolist (w (list 320 640))
  (dolist (h (list 32 64))
    (vera :tileset 0 :init :width w :height h :bpp 8 :num_tiles 1)
    (print (vera :tileset 0 :info))
    (vera :layer 0 :bitmap :tileset 0 :tile 0)
    (vera :tileset 0 :pixel :tile 0 :x 0 :y 0 :val 101)
    (vera :tileset 0 :pixel :tile 0 :x (- w 1) :y 0 :val 101)
    (vera :tileset 0 :pixel :tile 0 :x 0 :y (- h 1) :val 101)
    (vera :tileset 0 :pixel :tile 0 :x (- w 1) :y (- h 1) :val 101)
    (vera :irqline 0)
    (vera :linecapture :enable)
    (loop (if (= (vera :linecapture :enabled) 0) (return)))
    (print (vera :linecapture :pixel :x 0))
    (print (vera :linecapture :pixel :x 1))
    (print (vera :linecapture :pixel :x (- w 2)))
    (print (vera :linecapture :pixel :x (- w 1)))
    (vera :irqline 1)
    (vera :linecapture :enable)
    (loop (if (= (vera :linecapture :enabled) 0) (return)))
    (print (vera :linecapture :pixel :x 0))
    (print (vera :linecapture :pixel :x 1))
    (print (vera :linecapture :pixel :x (- w 2)))
    (print (vera :linecapture :pixel :x (- w 1)))
    (vera :irqline (- h 1))
    (vera :linecapture :enable)
    (loop (if (= (vera :linecapture :enabled) 0) (return)))
    (print (vera :linecapture :pixel :x 0))
    (print (vera :linecapture :pixel :x 1))
    (print (vera :linecapture :pixel :x (- w 2)))
    (print (vera :linecapture :pixel :x (- w 1)))
    (vera :irqline h)
    (vera :linecapture :enable)
    (loop (if (= (vera :linecapture :enabled) 0) (return)))
    (print (vera :linecapture :pixel :x 0))
    (print (vera :linecapture :pixel :x 1))
    (print (vera :linecapture :pixel :x (- w 2)))
    (print (vera :linecapture :pixel :x (- w 1)))
    (vera :tileset 0 :pixel :tile 0 :x 0 :y 0 :val 0)
    (vera :tileset 0 :pixel :tile 0 :x (- w 1) :y 0 :val 0)
    (vera :tileset 0 :pixel :tile 0 :x 0 :y (- h 1) :val 0)
    (vera :tileset 0 :pixel :tile 0 :x (- w 1) :y (- h 1) :val 0)
    (vera :tileset 0 :deinit)))






'end
