'start
(vera :display :enable)
(vera :sprites :enable)
(defvar w 64)
(dolist (h (list 8 16 32 64))
  (dolist (bpp (list 4 8))
    (vera :tileset 0 :width w :height h :bpp bpp :num-tiles 8)
    (vera :tileset 0 :info)
    (vera :sprite 1 :init)
    (vera :sprite 1 :tileset 0 :tile 2)
    (vera :sprite 1 :z +vera-sprite-z-l1+)
    (dotimes (yy h)
      (dotimes (xx (min w (1+ yy)))
        (vera-tileset-pixel 0 2 xx yy +vera-color-cyan+)))
    (vera :irqline 0)
    (vera :linecapture :enable)
    (loop (if (= (vera :linecapture :enabled) 0) (return)))
    (print (vera :linecapture :pixel :x 0))
    (print (vera :linecapture :pixel :x 1))
    (vera :irqline (- h 1))
    (vera :linecapture :enable)
    (loop (if (= (vera :linecapture :enabled) 0) (return)))
    (print (vera :linecapture :pixel :x 0))
    (print (vera :linecapture :pixel :x 7))
    (print (vera :linecapture :pixel :x (1- (min w h))))
    (print (vera :linecapture :pixel :x (min w h)))
    (vera :irqline h)
    (vera :linecapture :enable)
    (loop (if (= (vera :linecapture :enabled) 0) (return)))
    (print (vera :linecapture :pixel :x 0))
    (print (vera :linecapture :pixel :x 7))
    (print (vera :linecapture :pixel :x (1- (min w h))))
    (print (vera :linecapture :pixel :x (min w h)))
    (dotimes (yy h)
      (dotimes (xx (min w (1+ yy)))
        (vera-tileset-pixel 0 2 xx yy 0)))
    (vera :tileset 0 :deinit)))

<wait 20>
'end
