## This file is a general .xdc for the Arty A7-35 Rev. D
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

## Clock Constraints
set_property LOC E3 [get_ports {ext_clk_100}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext_clk_100}]

create_clock -name ext_clk_pin -period 10.00 [get_ports {ext_clk_100}]

#This is the JTAG TCK clock generated by the BSCANE2 primitive.
#Note that the JTAG top-level ports (incl. TCK) are not used in a synthesized design. They are driven by BSCANE2 instead.
#create_clock -period 1000.000 -name tck_o -waveform {0.000 500.000} [get_pins boxlambda_soc_inst/GENERATE_DEBUG_MODULE.dmi_jtag_inst/i_dmi_jtag_tap/i_tap_dtmcs/TCK]

#Set to quiet so we don't get a critical warning when LiteDRAM is not included in the build, in which case
#clkout1 does not exist.
#set_clock_groups -quiet -asynchronous -group [get_clocks -include_generated_clock main_clkout1] -group [get_clocks -include_generated_clock tck_o]

## Switches
set_property LOC A8    [get_ports {gpio[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[4]}]
set_property LOC C11   [get_ports {gpio[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[5]}]
set_property LOC C10   [get_ports {gpio[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[6]}]
set_property LOC A10   [get_ports {gpio[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[7]}]

## RGB LEDs
set_property LOC E1    [get_ports {pll_locked_led}]
set_property IOSTANDARD LVCMOS33 [get_ports {pll_locked_led}]
#set_property -dict {PACKAGE_PIN F6    IOSTANDARD LVCMOS33} [get_ports {led0_g}]
#set_property -dict {PACKAGE_PIN G6    IOSTANDARD LVCMOS33} [get_ports {led0_r}]
set_property LOC G4    [get_ports {init_done_led}]
set_property IOSTANDARD LVCMOS33 [get_ports {init_done_led}]
#set_property -dict {PACKAGE_PIN J4    IOSTANDARD LVCMOS33} [get_ports {led1_g}]
#set_property -dict {PACKAGE_PIN G3    IOSTANDARD LVCMOS33} [get_ports {led1_r}]
#set_property -dict {PACKAGE_PIN H4    IOSTANDARD LVCMOS33} [get_ports {led2_b}]
#set_property -dict {PACKAGE_PIN J2    IOSTANDARD LVCMOS33} [get_ports {led2_g}]
set_property LOC J3    [get_ports {init_err_led}]
set_property IOSTANDARD LVCMOS33 [get_ports {init_err_led}]
#set_property -dict {PACKAGE_PIN K2    IOSTANDARD LVCMOS33} [get_ports {led3_b}]
set_property LOC H6    [get_ports {sd_card_detect_led}]
set_property IOSTANDARD LVCMOS33 [get_ports {sd_card_detect_led}]
#set_property -dict {PACKAGE_PIN K1    IOSTANDARD LVCMOS33} [get_ports {wb_ctrl_err}]

## LEDs
set_property LOC H5    [get_ports {gpio[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[0]}]
set_property LOC J5    [get_ports {gpio[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[1]}]
set_property LOC T9    [get_ports {gpio[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[2]}]
set_property LOC T10   [get_ports {gpio[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[3]}]

## Buttons
set_property LOC D9    [get_ports {gpio[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[8]}]
set_property LOC C9    [get_ports {gpio[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[9]}]
set_property LOC B9    [get_ports {gpio[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[10]}]
set_property LOC B8    [get_ports {gpio[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[11]}]

## Pmod Header
set_property LOC G13   [get_ports {usb1_dp}]
set_property IOSTANDARD LVCMOS33 [get_ports {usb1_dp}]
set_property LOC B11   [get_ports {usb1_dm}]
set_property IOSTANDARD LVCMOS33 [get_ports {usb1_dm}]
set_property LOC A11   [get_ports {usb0_dp}]
set_property IOSTANDARD LVCMOS33 [get_ports {usb0_dp}]
set_property LOC D12   [get_ports {usb0_dm}]
set_property IOSTANDARD LVCMOS33 [get_ports {usb0_dm}]

#set_property -dict {PACKAGE_PIN D13   IOSTANDARD LVCMOS33} [get_ports {ja[4]}]
#set_property -dict {PACKAGE_PIN B18   IOSTANDARD LVCMOS33} [get_ports {ja[5]}]
#set_property -dict {PACKAGE_PIN A18   IOSTANDARD LVCMOS33} [get_ports {ja[6]}]
#set_property -dict {PACKAGE_PIN K16   IOSTANDARD LVCMOS33} [get_ports {ja[7]}]

## Pmod Header JB
set_property LOC E15   [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property LOC E16   [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property LOC D15   [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property LOC C15   [get_ports {vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property LOC J17   [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property LOC J18   [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property LOC K15   [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property LOC J15   [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]

## Pmod Header JC
set_property LOC U12   [get_ports {vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property LOC V12   [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property LOC V10   [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property LOC V11   [get_ports {vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property LOC U14   [get_ports {vga_hsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_hsync}]
set_property LOC V14   [get_ports {vga_vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_vsync}]
#set_property -dict {PACKAGE_PIN T13   IOSTANDARD LVCMOS33} [get_ports {jc[6]}]
#set_property -dict {PACKAGE_PIN U13   IOSTANDARD LVCMOS33} [get_ports {jc[7]}]

## Pmod Header JD
set_property LOC D4    [get_ports {sdspi_cs_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdspi_cs_n}]
set_property LOC D3    [get_ports {sdspi_mosi}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdspi_mosi}]
set_property LOC F4    [get_ports {sdspi_miso}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdspi_miso}]
set_property LOC F3    [get_ports {sdspi_sck}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdspi_sck}]
#set_property -dict {PACKAGE_PIN E2    IOSTANDARD LVCMOS33} [get_ports {jd[4]}]
#set_property -dict {PACKAGE_PIN D2    IOSTANDARD LVCMOS33} [get_ports {jd[5]}]
set_property LOC H2    [get_ports {sdspi_card_detect_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdspi_card_detect_n}]
#set_property -dict {PACKAGE_PIN G2    IOSTANDARD LVCMOS33} [get_ports {jd[7]}]

## USB-UART Interface
set_property LOC D10   [get_ports {uart_tx}]
set_property IOSTANDARD LVCMOS33 [get_ports {uart_tx}]
set_property LOC A9    [get_ports {uart_rx}]
set_property IOSTANDARD LVCMOS33 [get_ports {uart_rx}]

## ChipKit Outer Digital Header
set_property LOC V15   [get_ports {audio_out}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_out}]
set_property LOC U16   [get_ports {audio_gain}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_gain}]
#set_property -dict {PACKAGE_PIN P14   IOSTANDARD LVCMOS33} [get_ports {ck_io2}]
set_property LOC T11   [get_ports {audio_shutdown_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {audio_shutdown_n}]
set_property LOC R12   [get_ports {usb0_dm_snoop}]
set_property IOSTANDARD LVCMOS33 [get_ports {usb0_dm_snoop}]
set_property LOC T14   [get_ports {usb0_dp_snoop}]
set_property IOSTANDARD LVCMOS33 [get_ports {usb0_dp_snoop}]
set_property LOC T15   [get_ports {usb1_dm_snoop}]
set_property IOSTANDARD LVCMOS33 [get_ports {usb1_dm_snoop}]
set_property LOC T16   [get_ports {usb1_dp_snoop}]
set_property IOSTANDARD LVCMOS33 [get_ports {usb1_dp_snoop}]
#set_property -dict {PACKAGE_PIN N15   IOSTANDARD LVCMOS33} [get_ports {ck_io8}]
#set_property -dict {PACKAGE_PIN M16   IOSTANDARD LVCMOS33} [get_ports {ck_io9}]
#set_property -dict {PACKAGE_PIN V17   IOSTANDARD LVCMOS33} [get_ports {ck_io10}]
#set_property -dict {PACKAGE_PIN U18   IOSTANDARD LVCMOS33} [get_ports {ck_io11}]
#set_property -dict {PACKAGE_PIN R17   IOSTANDARD LVCMOS33} [get_ports {ck_io12}]
#set_property -dict {PACKAGE_PIN P17   IOSTANDARD LVCMOS33} [get_ports {ck_io13}]

## ChipKit Inner Digital Header
set_property LOC U11   [get_ports {gpio[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[12]}]
set_property LOC V16   [get_ports {gpio[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[13]}]
set_property LOC M13   [get_ports {gpio[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[14]}]
set_property LOC R10   [get_ports {gpio[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[15]}]
set_property LOC R11   [get_ports {gpio[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[16]}]
set_property LOC R13   [get_ports {gpio[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[17]}]
set_property LOC R15   [get_ports {gpio[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[18]}]
set_property LOC P15   [get_ports {gpio[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[19]}]
set_property LOC R16   [get_ports {gpio[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[20]}]
set_property LOC N16   [get_ports {gpio[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[21]}]
set_property LOC N14   [get_ports {gpio[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[22]}]
set_property LOC U17   [get_ports {gpio[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[23]}]
set_property LOC T18   [get_ports {gp_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {gp_clk}]
create_clock -add -name gp_clk_pin -period 40.00 [get_ports {gp_clk}]
#set_property -dict {PACKAGE_PIN R18   IOSTANDARD LVCMOS33} [get_ports {gpio[26]}]
#set_property -dict {PACKAGE_PIN P18   IOSTANDARD LVCMOS33} [get_ports {gpio[27]}]
#set_property -dict {PACKAGE_PIN N17   IOSTANDARD LVCMOS33} [get_ports {gpio[28]}]

## ChipKit Outer Analog Header - as Single-Ended Analog Inputs
## NOTE: These ports can be used as single-ended analog inputs with voltages from 0-3.3V (ChipKit analog pins A0-A5) or as digital I/O.
## WARNING: Do not use both sets of constraints at the same time!
## NOTE: The following constraints should be used with the XADC IP core when using these ports as analog inputs.
#set_property -dict {PACKAGE_PIN C5    IOSTANDARD LVCMOS33} [get_ports {vaux4_n}]
#set_property -dict {PACKAGE_PIN C6    IOSTANDARD LVCMOS33} [get_ports {vaux4_p}]
#set_property -dict {PACKAGE_PIN A5    IOSTANDARD LVCMOS33} [get_ports {vaux5_n}]
#set_property -dict {PACKAGE_PIN A6    IOSTANDARD LVCMOS33} [get_ports {vaux5_p}]
#set_property -dict {PACKAGE_PIN B4    IOSTANDARD LVCMOS33} [get_ports {vaux6_n}]
#set_property -dict {PACKAGE_PIN C4    IOSTANDARD LVCMOS33} [get_ports {vaux6_p}]
#set_property -dict {PACKAGE_PIN A1    IOSTANDARD LVCMOS33} [get_ports {vaux7_n}]
#set_property -dict {PACKAGE_PIN B1    IOSTANDARD LVCMOS33} [get_ports {vaux7_p}]
#set_property -dict {PACKAGE_PIN B2    IOSTANDARD LVCMOS33} [get_ports {vaux15_n}]
#set_property -dict {PACKAGE_PIN B3    IOSTANDARD LVCMOS33} [get_ports {vaux15_p}]
#set_property -dict {PACKAGE_PIN C14   IOSTANDARD LVCMOS33} [get_ports {vaux0_n}]
#set_property -dict {PACKAGE_PIN D14   IOSTANDARD LVCMOS33} [get_ports {vaux0_p}]
## ChipKit Outer Analog Header - as Digital I/O
## NOTE: the following constraints should be used when using these ports as digital I/O.
#set_property -dict {PACKAGE_PIN F5    IOSTANDARD LVCMOS33} [get_ports {ck_a0}]
#set_property -dict {PACKAGE_PIN D8    IOSTANDARD LVCMOS33} [get_ports {ck_a1}]
#set_property -dict {PACKAGE_PIN C7    IOSTANDARD LVCMOS33} [get_ports {ck_a2}]
#set_property -dict {PACKAGE_PIN E7    IOSTANDARD LVCMOS33} [get_ports {ck_a3}]
#set_property -dict {PACKAGE_PIN D7    IOSTANDARD LVCMOS33} [get_ports {ck_a4}]
#set_property -dict {PACKAGE_PIN D5    IOSTANDARD LVCMOS33} [get_ports {ck_a5}]

## ChipKit Inner Analog Header - as Differential Analog Inputs
## NOTE: These ports can be used as differential analog inputs with voltages from 0-1.0V (ChipKit Analog pins A6-A11) or as digital I/O.
## WARNING: Do not use both sets of constraints at the same time!
## NOTE: The following constraints should be used with the XADC core when using these ports as analog inputs.
#set_property -dict {PACKAGE_PIN B7    IOSTANDARD LVCMOS33} [get_ports {vaux12_p}]
#set_property -dict {PACKAGE_PIN B6    IOSTANDARD LVCMOS33} [get_ports {vaux12_n}]
#set_property -dict {PACKAGE_PIN E6    IOSTANDARD LVCMOS33} [get_ports {vaux13_p}]
#set_property -dict {PACKAGE_PIN E5    IOSTANDARD LVCMOS33} [get_ports {vaux13_n}]
#set_property -dict {PACKAGE_PIN A4    IOSTANDARD LVCMOS33} [get_ports {vaux14_p}]
#set_property -dict {PACKAGE_PIN A3    IOSTANDARD LVCMOS33} [get_ports {vaux14_n}]
## ChipKit Inner Analog Header - as Digital I/O
## NOTE: the following constraints should be used when using the inner analog header ports as digital I/O.
#set_property -dict {PACKAGE_PIN B7    IOSTANDARD LVCMOS33} [get_ports {ck_io20}]
#set_property -dict {PACKAGE_PIN B6    IOSTANDARD LVCMOS33} [get_ports {ck_io21}]
#set_property -dict {PACKAGE_PIN E6    IOSTANDARD LVCMOS33} [get_ports {ck_io22}]
#set_property -dict {PACKAGE_PIN E5    IOSTANDARD LVCMOS33} [get_ports {ck_io23}]
#set_property -dict {PACKAGE_PIN A4    IOSTANDARD LVCMOS33} [get_ports {ck_io24}]
#set_property -dict {PACKAGE_PIN A3    IOSTANDARD LVCMOS33} [get_ports {ck_io25}]

## ChipKit SPI
#set_property -dict {PACKAGE_PIN G1    IOSTANDARD LVCMOS33} [get_ports {ck_miso}]
#set_property -dict {PACKAGE_PIN H1    IOSTANDARD LVCMOS33} [get_ports {ck_mosi}]
#set_property -dict {PACKAGE_PIN F1    IOSTANDARD LVCMOS33} [get_ports {ck_sck}]
#set_property -dict {PACKAGE_PIN C1    IOSTANDARD LVCMOS33} [get_ports {ck_ss}]

## ChipKit I2C
set_property LOC L18   [get_ports {i2c_scl}]
set_property IOSTANDARD LVCMOS33 [get_ports {i2c_scl}]
set_property LOC M18   [get_ports {i2c_sda}]
set_property IOSTANDARD LVCMOS33 [get_ports {i2c_sda}]
set_property LOC A14   [get_ports {i2c_scl_pup}]
set_property IOSTANDARD LVCMOS33 [get_ports {i2c_scl_pup}]
set_property LOC A13   [get_ports {i2c_sda_pup}]
set_property IOSTANDARD LVCMOS33 [get_ports {i2c_sda_pup}]

## Misc. ChipKit Ports
#set_property -dict {PACKAGE_PIN M17   IOSTANDARD LVCMOS33} [get_ports {ck_ioa}]
set_property LOC C2    [get_ports {ext_rst_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext_rst_n}]

## SMSC Ethernet PHY
#set_property -dict {PACKAGE_PIN D17   IOSTANDARD LVCMOS33} [get_ports {eth_col}]
#set_property -dict {PACKAGE_PIN G14   IOSTANDARD LVCMOS33} [get_ports {eth_crs}]
#set_property -dict {PACKAGE_PIN F16   IOSTANDARD LVCMOS33} [get_ports {eth_mdc}]
#set_property -dict {PACKAGE_PIN K13   IOSTANDARD LVCMOS33} [get_ports {eth_mdio}]
#set_property -dict {PACKAGE_PIN G18   IOSTANDARD LVCMOS33} [get_ports {eth_ref_clk}]
#set_property -dict {PACKAGE_PIN C16   IOSTANDARD LVCMOS33} [get_ports {eth_rstn}]
#set_property -dict {PACKAGE_PIN F15   IOSTANDARD LVCMOS33} [get_ports {eth_rx_clk}]
#set_property -dict {PACKAGE_PIN G16   IOSTANDARD LVCMOS33} [get_ports {eth_rx_dv}]
#set_property -dict {PACKAGE_PIN D18   IOSTANDARD LVCMOS33} [get_ports {eth_rxd[0]}]
#set_property -dict {PACKAGE_PIN E17   IOSTANDARD LVCMOS33} [get_ports {eth_rxd[1]}]
#set_property -dict {PACKAGE_PIN E18   IOSTANDARD LVCMOS33} [get_ports {eth_rxd[2]}]
#set_property -dict {PACKAGE_PIN G17   IOSTANDARD LVCMOS33} [get_ports {eth_rxd[3]}]
#set_property -dict {PACKAGE_PIN C17   IOSTANDARD LVCMOS33} [get_ports {eth_rxerr}]
#set_property -dict {PACKAGE_PIN H16   IOSTANDARD LVCMOS33} [get_ports {eth_tx_clk}]
#set_property -dict {PACKAGE_PIN H15   IOSTANDARD LVCMOS33} [get_ports {eth_tx_en}]
#set_property -dict {PACKAGE_PIN H14   IOSTANDARD LVCMOS33} [get_ports {eth_txd[0]}]
#set_property -dict {PACKAGE_PIN J14   IOSTANDARD LVCMOS33} [get_ports {eth_txd[1]}]
#set_property -dict {PACKAGE_PIN J13   IOSTANDARD LVCMOS33} [get_ports {eth_txd[2]}]
#set_property -dict {PACKAGE_PIN H17   IOSTANDARD LVCMOS33} [get_ports {eth_txd[3]}]

## SPI Flash
# set_property IOB TRUE [get_cells {boxlambda_soc_inst/GENERATE_SPIFLASH_MODULE.spiflash_inst/o_spi_cs_n_reg }];
# set_property IOB TRUE [get_cells {boxlambda_soc_inst/GENERATE_SPIFLASH_MODULE.spiflash_inst/o_spi_sck_reg }];
set_property LOC L13   [get_ports {spiflash_cs_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {spiflash_cs_n}]
set_property LOC K17   [get_ports {spiflash_mosi}]
set_property IOSTANDARD LVCMOS33 [get_ports {spiflash_mosi}]
set_property LOC K18   [get_ports {spiflash_miso}]
set_property IOSTANDARD LVCMOS33 [get_ports {spiflash_miso}]
#set_property -dict {PACKAGE_PIN L14   IOSTANDARD LVCMOS33} [get_ports {qspi_dq[2]}]
#set_property -dict {PACKAGE_PIN M14   IOSTANDARD LVCMOS33} [get_ports {qspi_dq[3]}]
set_property LOC L16   [get_ports {spiflash_sck}]
set_property IOSTANDARD LVCMOS33 [get_ports {spiflash_sck}]

## Power Measurements
#set_property -dict {PACKAGE_PIN B17   IOSTANDARD LVCMOS33   } [get_ports {vsnsvu_n}]
#set_property -dict {PACKAGE_PIN B16   IOSTANDARD LVCMOS33   } [get_ports {vsnsvu_p}]
#set_property -dict {PACKAGE_PIN B12   IOSTANDARD LVCMOS33   } [get_ports {vsns5v0_n}]
#set_property -dict {PACKAGE_PIN C12   IOSTANDARD LVCMOS33   } [get_ports {vsns5v0_p}]
#set_property -dict {PACKAGE_PIN F14   IOSTANDARD LVCMOS33   } [get_ports {isns5v0_n}]
#set_property -dict {PACKAGE_PIN F13   IOSTANDARD LVCMOS33   } [get_ports {isns5v0_p}]
#set_property -dict {PACKAGE_PIN A16   IOSTANDARD LVCMOS33   } [get_ports {isns0v95_n}]
#set_property -dict {PACKAGE_PIN A15   IOSTANDARD LVCMOS33   } [get_ports {isns0v95_p}]

# ddram:0.a
set_property LOC R2 [get_ports {ddram_a[0]}]
set_property SLEW FAST [get_ports {ddram_a[0]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_a[0]}]

#
set_property LOC M6 [get_ports {ddram_a[1]}]
set_property SLEW FAST [get_ports {ddram_a[1]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_a[1]}]

#
set_property LOC N4 [get_ports {ddram_a[2]}]
set_property SLEW FAST [get_ports {ddram_a[2]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_a[2]}]

#
set_property LOC T1 [get_ports {ddram_a[3]}]
set_property SLEW FAST [get_ports {ddram_a[3]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_a[3]}]

#
set_property LOC N6 [get_ports {ddram_a[4]}]
set_property SLEW FAST [get_ports {ddram_a[4]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_a[4]}]

#
set_property LOC R7 [get_ports {ddram_a[5]}]
set_property SLEW FAST [get_ports {ddram_a[5]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_a[5]}]

#
set_property LOC V6 [get_ports {ddram_a[6]}]
set_property SLEW FAST [get_ports {ddram_a[6]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_a[6]}]

#
set_property LOC U7 [get_ports {ddram_a[7]}]
set_property SLEW FAST [get_ports {ddram_a[7]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_a[7]}]

#
set_property LOC R8 [get_ports {ddram_a[8]}]
set_property SLEW FAST [get_ports {ddram_a[8]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_a[8]}]

#
set_property LOC V7 [get_ports {ddram_a[9]}]
set_property SLEW FAST [get_ports {ddram_a[9]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_a[9]}]

#
set_property LOC R6 [get_ports {ddram_a[10]}]
set_property SLEW FAST [get_ports {ddram_a[10]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_a[10]}]

#
set_property LOC U6 [get_ports {ddram_a[11]}]
set_property SLEW FAST [get_ports {ddram_a[11]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_a[11]}]

#
set_property LOC T6 [get_ports {ddram_a[12]}]
set_property SLEW FAST [get_ports {ddram_a[12]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_a[12]}]

#
set_property LOC T8 [get_ports {ddram_a[13]}]
set_property SLEW FAST [get_ports {ddram_a[13]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_a[13]}]

#
set_property LOC R1 [get_ports {ddram_ba[0]}]
set_property SLEW FAST [get_ports {ddram_ba[0]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_ba[0]}]

#
set_property LOC P4 [get_ports {ddram_ba[1]}]
set_property SLEW FAST [get_ports {ddram_ba[1]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_ba[1]}]

#
set_property LOC P2 [get_ports {ddram_ba[2]}]
set_property SLEW FAST [get_ports {ddram_ba[2]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_ba[2]}]

#
set_property LOC P3 [get_ports {ddram_ras_n}]
set_property SLEW FAST [get_ports {ddram_ras_n}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_ras_n}]

#
set_property LOC M4 [get_ports {ddram_cas_n}]
set_property SLEW FAST [get_ports {ddram_cas_n}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_cas_n}]

#
set_property LOC P5 [get_ports {ddram_we_n}]
set_property SLEW FAST [get_ports {ddram_we_n}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_we_n}]

#
set_property LOC U8 [get_ports {ddram_cs_n}]
set_property SLEW FAST [get_ports {ddram_cs_n}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_cs_n}]

#
set_property LOC L1 [get_ports {ddram_dm[0]}]
set_property SLEW FAST [get_ports {ddram_dm[0]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dm[0]}]

#
set_property LOC U1 [get_ports {ddram_dm[1]}]
set_property SLEW FAST [get_ports {ddram_dm[1]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dm[1]}]

#
set_property LOC K5 [get_ports {ddram_dq[0]}]
set_property SLEW FAST [get_ports {ddram_dq[0]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[0]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[0]}]

#
set_property LOC L3 [get_ports {ddram_dq[1]}]
set_property SLEW FAST [get_ports {ddram_dq[1]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[1]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[1]}]

#
set_property LOC K3 [get_ports {ddram_dq[2]}]
set_property SLEW FAST [get_ports {ddram_dq[2]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[2]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[2]}]

#
set_property LOC L6 [get_ports {ddram_dq[3]}]
set_property SLEW FAST [get_ports {ddram_dq[3]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[3]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[3]}]

#
set_property LOC M3 [get_ports {ddram_dq[4]}]
set_property SLEW FAST [get_ports {ddram_dq[4]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[4]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[4]}]

#
set_property LOC M1 [get_ports {ddram_dq[5]}]
set_property SLEW FAST [get_ports {ddram_dq[5]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[5]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[5]}]

#
set_property LOC L4 [get_ports {ddram_dq[6]}]
set_property SLEW FAST [get_ports {ddram_dq[6]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[6]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[6]}]

#
set_property LOC M2 [get_ports {ddram_dq[7]}]
set_property SLEW FAST [get_ports {ddram_dq[7]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[7]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[7]}]

#
set_property LOC V4 [get_ports {ddram_dq[8]}]
set_property SLEW FAST [get_ports {ddram_dq[8]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[8]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[8]}]

#
set_property LOC T5 [get_ports {ddram_dq[9]}]
set_property SLEW FAST [get_ports {ddram_dq[9]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[9]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[9]}]

#
set_property LOC U4 [get_ports {ddram_dq[10]}]
set_property SLEW FAST [get_ports {ddram_dq[10]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[10]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[10]}]

#
set_property LOC V5 [get_ports {ddram_dq[11]}]
set_property SLEW FAST [get_ports {ddram_dq[11]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[11]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[11]}]

#
set_property LOC V1 [get_ports {ddram_dq[12]}]
set_property SLEW FAST [get_ports {ddram_dq[12]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[12]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[12]}]

#
set_property LOC T3 [get_ports {ddram_dq[13]}]
set_property SLEW FAST [get_ports {ddram_dq[13]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[13]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[13]}]

#
set_property LOC U3 [get_ports {ddram_dq[14]}]
set_property SLEW FAST [get_ports {ddram_dq[14]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[14]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[14]}]

#
set_property LOC R3 [get_ports {ddram_dq[15]}]
set_property SLEW FAST [get_ports {ddram_dq[15]}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_dq[15]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dq[15]}]

#
set_property LOC N2 [get_ports {ddram_dqs_p[0]}]
set_property SLEW FAST [get_ports {ddram_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL135 [get_ports {ddram_dqs_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dqs_p[0]}]

#
set_property LOC U2 [get_ports {ddram_dqs_p[1]}]
set_property SLEW FAST [get_ports {ddram_dqs_p[1]}]
set_property IOSTANDARD DIFF_SSTL135 [get_ports {ddram_dqs_p[1]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dqs_p[1]}]

#
set_property LOC N1 [get_ports {ddram_dqs_n[0]}]
set_property SLEW FAST [get_ports {ddram_dqs_n[0]}]
set_property IOSTANDARD DIFF_SSTL135 [get_ports {ddram_dqs_n[0]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dqs_n[0]}]

#
set_property LOC V2 [get_ports {ddram_dqs_n[1]}]
set_property SLEW FAST [get_ports {ddram_dqs_n[1]}]
set_property IOSTANDARD DIFF_SSTL135 [get_ports {ddram_dqs_n[1]}]
set_property IN_TERM UNTUNED_SPLIT_40 [get_ports {ddram_dqs_n[1]}]

#
set_property LOC U9 [get_ports {ddram_clk_p}]
set_property SLEW FAST [get_ports {ddram_clk_p}]
set_property IOSTANDARD DIFF_SSTL135 [get_ports {ddram_clk_p}]

#
set_property LOC V9 [get_ports {ddram_clk_n}]
set_property SLEW FAST [get_ports {ddram_clk_n}]
set_property IOSTANDARD DIFF_SSTL135 [get_ports {ddram_clk_n}]

#
set_property LOC N5 [get_ports {ddram_cke}]
set_property SLEW FAST [get_ports {ddram_cke}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_cke}]

#
set_property LOC R5 [get_ports {ddram_odt}]
set_property SLEW FAST [get_ports {ddram_odt}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_odt}]

#
set_property LOC K6 [get_ports {ddram_reset_n}]
set_property SLEW FAST [get_ports {ddram_reset_n}]
set_property IOSTANDARD SSTL135 [get_ports {ddram_reset_n}]

#
#
#
# set_false_path -quiet -to [get_pins -filter {REF_PIN_NAME == PRE} -of_objects [get_cells -hierarchical -filter {ars_ff1 == TRUE || ars_ff2 == TRUE}]]

# set_max_delay 2 -quiet -from [get_pins -filter {REF_PIN_NAME == C} -of_objects [get_cells -hierarchical -filter {ars_ff1 == TRUE}]] -to [get_pins -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -filter {ars_ff2 == TRUE}]]

#
#
#

# set_property INTERNAL_VREF 0.675 [get_iobanks 34]
# set_property CONFIG_VOLTAGE 3.3 [current_design]
# set_property CFGBVS VCCO [current_design]

# The 12MHz USB clock domain is asynchronous relative to the 100MHz clock domain going into
# LiteDRAM producing the 50 and 100MHz sysclk trees.
# set_clock_groups -asynchronous -group [get_clocks -include_generated_clock clk_12_unbuf] -group [get_clocks -include_generated_clock clk_100_unbuf]

# Bitstream configuration options
# set_property BITSTREAM.GENERAL.COMPRESS False [current_design]
# set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
# set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR No [current_design]
# set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
# set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
