#Path to the root of the repository
TOP_DIR := ../..

#Flag indicating Out-of-Context Synthesis of given component
OOC = ibex

#Include common Make flags and rules
include $(TOP_DIR)/build_sys/common.mk

