#ifndef VERA_H_
#define VERA_H

#define VERA_BASE 0

#define VERA_ADDR_L   	  (VERA_BASE + 0x00)
#define VERA_ADDR_M   	  (VERA_BASE + 0x01)
#define VERA_ADDR_H   	  (VERA_BASE + 0x02)
#define VERA_DATA0        (VERA_BASE + 0x03)
#define VERA_DATA1        (VERA_BASE + 0x04)
#define VERA_CTRL         (VERA_BASE + 0x05)

#define VERA_IEN          (VERA_BASE + 0x06)
#define VERA_ISR          (VERA_BASE + 0x07)
#define VERA_IRQ_LINE_L   (VERA_BASE + 0x08)

#define VERA_DC_VIDEO     (VERA_BASE + 0x09)
#define VERA_DC_HSCALE    (VERA_BASE + 0x0A)
#define VERA_DC_VSCALE    (VERA_BASE + 0x0B)
#define VERA_DC_BORDER    (VERA_BASE + 0x0C)

#define VERA_DC_HSTART    (VERA_BASE + 0x09)
#define VERA_DC_HSTOP     (VERA_BASE + 0x0A)
#define VERA_DC_VSTART    (VERA_BASE + 0x0B)
#define VERA_DC_VSTOP     (VERA_BASE + 0x0C)

#define VERA_L0_CONFIG    (VERA_BASE + 0x0D)
#define VERA_L0_MAPBASE   (VERA_BASE + 0x0E)
#define VERA_L0_TILEBASE  (VERA_BASE + 0x0F)
#define VERA_L0_HSCROLL_L (VERA_BASE + 0x10)
#define VERA_L0_HSCROLL_H (VERA_BASE + 0x11)
#define VERA_L0_VSCROLL_L (VERA_BASE + 0x12)
#define VERA_L0_VSCROLL_H (VERA_BASE + 0x13)

#define VERA_L1_CONFIG    (VERA_BASE + 0x14)
#define VERA_L1_MAPBASE   (VERA_BASE + 0x15)
#define VERA_L1_TILEBASE  (VERA_BASE + 0x16)
#define VERA_L1_HSCROLL_L (VERA_BASE + 0x17)
#define VERA_L1_HSCROLL_H (VERA_BASE + 0x18)
#define VERA_L1_VSCROLL_L (VERA_BASE + 0x19)
#define VERA_L1_VSCROLL_H (VERA_BASE + 0x1A)

#define VERA_PALETTE_BASE 0x1FA00
#define VERA_SPRITES_BASE 0x1FC00

#endif //VERA_H