# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/epsilon/work/boxlambda/gw/dfx/dfx_controller/dfx_controller_0/dfx_controller_0.xci
# IP: The module: 'dfx_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/epsilon/work/boxlambda/gw/dfx/dfx_controller/dfx_controller_0/dfx_controller_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/epsilon/work/boxlambda/gw/dfx/dfx_controller/dfx_controller_0/dfx_controller_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/epsilon/work/boxlambda/gw/dfx/dfx_controller/dfx_controller_0/dfx_controller_0.xci
# IP: The module: 'dfx_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/epsilon/work/boxlambda/gw/dfx/dfx_controller/dfx_controller_0/dfx_controller_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/epsilon/work/boxlambda/gw/dfx/dfx_controller/dfx_controller_0/dfx_controller_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
