#include <getopt.h>
#include <fcntl.h>

// For std::unique_ptr
#include <memory>

#include <string>
#include <stdio.h>

// Include common routines
#include <verilated.h>

// Include model header, generated from Verilating "top.v"
#include "Vmodel.h"

#include "verilated_fst_c.h"

//To get access to the verilated model internals.
#include "Vmodel___024root.h"

// From wbuart32
#include "uartsim.h"

// From riscv-dbg
#include "sim_jtag.h"

// SDSPI simulation model
#include "sdspisim.h"

//We set GPIO bits 7:4 to 0xf to indicate to RISCV SW that this is a simulation.
#define GPIO_SIM_INDICATOR 0x0000f0

// SD card image holding the song .ym file to play back.
const char	DEFAULT_SDIMAGE_FILENAME[] = "sdcard.img";

//The pcm_out file will contain the 16-bit PCM output data in python array format generated by the Verilator model.
const char	DEFAULT_PCM_OUT_FILENAME[] = "pcm_out.py";
FILE *pcmFile = 0;
int pcmOutputCounter = 0; //Used to implement divide-by-1024 to get a 48.8kHz rate.

bool overflowDetected = false;

bool tracing_enable = false;

//Uart co-simulation from wbuart32.
std::unique_ptr<UARTSIM> uart{new UARTSIM(0)};

//SDPI co-simulation
std::unique_ptr<SDSPISIM>	sdspi{new SDSPISIM(true)};

// Used for tracing.
VerilatedFstC* tfp = new VerilatedFstC;

// Construct a VerilatedContext to hold simulation time, etc.
// Multiple modules (made later below with Vtop) may share the same
// context to share time, or modules may have different contexts if
// they should be independent from each other.
std::unique_ptr<VerilatedContext> contextp{new VerilatedContext};

// Construct the Verilated model, from Vmodel.h generated from Verilating this project.
// Using unique_ptr is similar to "Vmodel* top = new Vmodel" then deleting at end.
std::unique_ptr<Vmodel> top{new Vmodel{contextp.get()}};

//Initialize UART rx and tx change detector
std::string uartRxStringPrev;

// Legacy function required only so linking works on Cygwin and MSVC++
double sc_time_stamp() { return 0; }

//Clean-up logic.
static void cleanup() {
  //Close PCM output file
  fprintf(pcmFile, "]\n");
  fclose(pcmFile);

  //Close trace file.
  if (tracing_enable)
    tfp->close();

  // Final model cleanup
  top->final();
}

//Returns 0 if OK, negative on error.
static int setupSDSPISim(const char *sdcard_image) {
		if (0 != access(sdcard_image, R_OK)) {
			printf("SIM: Cannot open %s for reading\n", sdcard_image);
			return -1;
		} if (0 != access(sdcard_image, W_OK)) {
			printf("SIM: Cannot open %s for writing\n", sdcard_image);
			return -2;
		}

		sdspi->load(sdcard_image);
    return 0;
}

//Advance simulation by one clock cycle
static void tick(void) {
  //Tick twice: Input clock is 100MHz, BoxLambda's system clock runs at 50MHz.
  //->Advance two input clock cycles at a time.
  for (int ii=0; ii<2;ii++) {
    //High phase
    top->clk_i = 1;
    contextp->timeInc(1);
    top->eval();
    if (tracing_enable)
      tfp->dump(contextp->time());

    //Low phase
    top->clk_i = 0;
    contextp->timeInc(1);
    top->eval();
    if (tracing_enable)
      tfp->dump(contextp->time());
  }

  //Feed SDSPI co-sim
  top->sdspi_miso = (*sdspi)(top->sdspi_cs_n, top->sdspi_sck, top->sdspi_mosi);

  top->gp_in = GPIO_SIM_INDICATOR; //Indicate to SW that this is a simulation.

  //Feed our model's uart_tx signal and baud rate to the UART co-simulator.
  //and feed the UART co-simulator output to our model
  top->uart_rx = (*uart)(top->uart_tx,
  top->rootp->sim_main__DOT__dut__DOT__boxlambda_soc_inst__DOT__wbuart_inst__DOT__uart_setup);

  //Detect and print changes to UART
  if (uart->get_rx_string().back() == '\n')  {
    printf("DUT: %s", uart->get_rx_string().c_str());

    //Update change detectors
    uartRxStringPrev = uart->get_rx_string();

    uart->clear_rx_string();
  }

  //Detect DAC accumulator overflows
  if (top->acc1_overflow) {
    overflowDetected = 1;
    printf("SIM: time: %ld: acc1 overflow!\n", contextp->time());
  }

  //Detect DAC accumulator overflows
  if (top->acc2_overflow) {
    overflowDetected = 1;
    printf("SIM: time: %ld: acc2 overflow!\n", contextp->time());
  }

  ++pcmOutputCounter;
  if (pcmOutputCounter == 1024) {
    pcmOutputCounter = 0;
    fprintf(pcmFile, "  %d,\n", top->pcm_out);
  }
}

int main(int argc, char** argv, char** env) {
    // Prevent unused variable warnings
    if (false && argc && argv && env) {}

    // Set debug level, 0 is off, 9 is highest presently used
    // May be overridden by commandArgs argument parsing
    contextp->debug(0);

    // Randomization reset policy
    // May be overridden by commandArgs argument parsing
    contextp->randReset(2);

    // Verilator must compute traced signals
    contextp->traceEverOn(true);

    // Pass arguments so Verilated code can see them, e.g. $value$plusargs
    // This needs to be called before you create any model
    contextp->commandArgs(argc, argv);

    bool attach_debugger = false;
    bool interactive_mode = false;
    const char *pcm_filename = DEFAULT_PCM_OUT_FILENAME;
    const char *sd_img_filename = DEFAULT_SDIMAGE_FILENAME;

    // Command line processing
    for(;;) {
      switch(getopt(argc, argv, "aithf:s:")) {
      case 'a':
        attach_debugger = true;
        continue;
      case 'f':
        pcm_filename = optarg;
        continue;
      case 's':
        sd_img_filename = optarg;
        continue;
      case 't':
        printf("SIM: Tracing enabled\n");
        tracing_enable = true;
        continue;
      case 'i':
        printf("SIM: Interactive mode enabled\n");
        interactive_mode = true;
        continue;
      case '?':
      case 'h':
      default :
        printf("SIM: \nVmodel Usage:\n");
        printf("SIM: -h: print this help\n");
        printf("SIM: -a: attach debugger.\n");
        printf("SIM: -t: enable tracing.\n");
        printf("SIM: -i: enable interactive mode.\n");
        printf("SIM: -f <output pcm file>\n");
        printf("SIM: -s <sdcard.img>\n");
        return 0;
        break;

      case -1:
        break;
      }

      break;
    }

    //Trace file
    if (tracing_enable) {
      top->trace(tfp, 99); //Trace 99 levels deep.
      tfp->open("simx.fst");
    }

    jtag_set_bypass(!attach_debugger);

    printf("SIM: SD Image File: %s\n", sd_img_filename);

    if(setupSDSPISim(sd_img_filename) < 0) {
      cleanup();
      exit(-1);
    }

    printf("SIM: PCM Output File: %s\n", pcm_filename);
    pcmFile = fopen(pcm_filename, "w");
    if (pcmFile == NULL) {
      printf("SIM: Unable to open PCM output file\n");
      return -1;
    }
    fprintf(pcmFile, "pcmdata = [\n");

    //Set SD card detect.
    top->sdspi_card_detect = 1;
    // Assert reset for a couple of clock cycles.
    top->clk_i = 0;
    top->uart_rx = 0;
    //Take system out of reset.
    top->rst_ni = 1;

    // When not in interactive mode, simulate for 1000000000 timeprecision periods
    while (interactive_mode || (contextp->time() < 1000000000)) {
        // Evaluate model
        tick();
    }

    cleanup();

    // Checks for automated testing.
    int res = 0;
    std::string uartCheckString("Starting playback...");

    if (uartRxStringPrev.find(uartCheckString) == std::string::npos) {
      printf("SIM: Test failed\n");
      printf("SIM: Expected: %s\n", uartCheckString.c_str());
      printf("SIM: Received: %s\n", uartRxStringPrev.c_str());

      res = 1;
    }

    if (!overflowDetected) {
      printf("SIM: No overflows detected.\n");
    }
    else {
      res = 1;
    }

    if (res == 0) {
      printf("SIM: Test passed.\n");
    }

    return res;
}
