
const char LispLibrary[] =  R"lisplibrary(
(defvar VERA_IRQ_VSYNC 1)
(defvar VERA_IRQ_LINE 2)
(defvar VERA_IRQ_SPRCOL 4)

(defvar VERA_SCANLINE_VISIBLE_MAX 479)
(defvar VERA_SCANLINE_MAX 524)

(defvar VERA_HSTOP_MAX 1023)
(defvar VERA_VSTOP_MAX 1023)

(defvar VERA_MAX_NUM_TILES_IN_TILESET 1024)

(defvar VERA_NUM_LAYERS 2)

(defvar VERA_NUM_SPRITE_BANKS 2)
(defvar VERA_NUM_SPRITES_IN_BANK 64)
(defvar VERA_NUM_SPRITES (* VERA_NUM_SPRITE_BANKS VERA_NUM_SPRITES_IN_BANK))
(defvar VERA_MAX_SPRITE_ID 127)

(defvar VERA_NUM_MAPS 32)
(defvar VERA_NUM_TILESETS 32)

(defvar VERA_COLOR_BLACK 0)
(defvar VERA_COLOR_WHITE 1)
(defvar VERA_COLOR_RED 2)
(defvar VERA_COLOR_CYAN 3)
(defvar VERA_COLOR_PURPLE 4)
(defvar VERA_COLOR_GREEN 5)
(defvar VERA_COLOR_BLUE 6)
(defvar VERA_COLOR_YELLOW 7)
(defvar VERA_COLOR_ORANGE 8)
(defvar VERA_COLOR_BROWN 9)
(defvar VERA_COLOR_LIGHT_RED 10)
(defvar VERA_COLOR_DARK_GREY 11)
(defvar VERA_COLOR_GREY 12)
(defvar VERA_COLOR_LIGHT_GREEN 13)
(defvar VERA_COLOR_LIGHT_BLUE 14)
(defvar VERA_COLOR_LIGHT_GREY 15)

(defvar VERA_COLOR_GRAYSCALE_0 16)
(defvar VERA_COLOR_GRAYSCALE_1 17)
(defvar VERA_COLOR_GRAYSCALE_2 18)
(defvar VERA_COLOR_GRAYSCALE_3 19)
(defvar VERA_COLOR_GRAYSCALE_4 20)
(defvar VERA_COLOR_GRAYSCALE_5 21)
(defvar VERA_COLOR_GRAYSCALE_6 22)
(defvar VERA_COLOR_GRAYSCALE_7 23)
(defvar VERA_COLOR_GRAYSCALE_8 24)
(defvar VERA_COLOR_GRAYSCALE_9 25)
(defvar VERA_COLOR_GRAYSCALE_10 26)
(defvar VERA_COLOR_GRAYSCALE_11 27)
(defvar VERA_COLOR_GRAYSCALE_12 28)
(defvar VERA_COLOR_GRAYSCALE_13 29)
(defvar VERA_COLOR_GRAYSCALE_14 30)
(defvar VERA_COLOR_GRAYSCALE_15 31)

(defvar VERA_MAP_TYPE_TXT16 0)
(defvar VERA_MAP_TYPE_TXT256 1)
(defvar VERA_MAP_TYPE_TILE 2)

(defvar VERA_SPRITE_Z_DIS 0)
(defvar VERA_SPRITE_Z_BG_L0 1)
(defvar VERA_SPRITE_Z_L0_L1 2)
(defvar VERA_SPRITE_Z_L1 3)

(defvar VERA_MAPENTRY_HFLIP_MASK 1024)
(defvar VERA_MAPENTRY_VFLIP_MASK 2048)
(defvar VERA_MAPENTRY_PAL_OFFSET_SHIFT 12)

)lisplibrary";

