#! /bin/bash

#This script is used by the build system. It does the following:
#- It copies any .mem files referenced in the Bender manifest to the GW build tree, e.g. palette.mem.
#- It generates a tcl sub script for mem files to be included in the main vivado.tcl script.
#This script does not handle the .mem file generated by the SW build system. That's handled in a separate,
#post-synthesis build step.

if [[ "$#" < 3  || "$1" == "-h" ]]
then
  echo "$0 <src dir> <script file> vivado|verilator"
  exit 1
fi

SRC_DIR=$1
SCRIPT_FILE_NAME=$2
#verilator or vivado
TARGET=$3

echo "#Memory files" > $SCRIPT_FILE_NAME

MEM_FILE_LIST=`bender -d $SRC_DIR script -t memory_$TARGET flist`

#Remove the generated Bender.lock file to keep the source tree clean.
rm -f $SRC_DIR/Bender.lock

for f in $MEM_FILE_LIST
do
	cp $f .
  echo "add_files -norecurse $f" >> $SCRIPT_FILE_NAME
done

