#! /bin/bash

#This script does the following:
#- It copies a .mem file generated by the SW build system (e.g. hello_world.mem) to its proper place and name in
#  the GW build tree, e.g. spram.mem.
#- It copies any .mem files referenced in the Bender manifest to the GW build tree, e.g. palette.mem.
#- It generates a tcl sub script to be included in the main vivado.tcl script.
#This script is used by the build system.

if [[ "$#" == 0  || "$1" == "-h" ]]
then
  echo "$0 <src dir> <script file> [<input mem file> <output mem file>]"
  exit 1
fi

SRC_DIR=$1
SCRIPT_FILE_NAME=$2

rm -f $SCRIPT_FILE_NAME.tmp

MEM_FILE_LIST=`bender -d $SRC_DIR script -t memory flist`
for f in $MEM_FILE_LIST
do
	cp $f .
  echo "add_files -norecurse $f" >> $SCRIPT_FILE_NAME.tmp
done

if [ -n "$3" ] && [ -n "$4" ]
then
  IN_MEM_FILE=$3
  OUT_MEM_FILE=$4
  echo "add_files -norecurse $OUT_MEM_FILE"
  cp $IN_MEM_FILE $OUT_MEM_FILE
  echo "add_files -norecurse $OUT_MEM_FILE" >> $SCRIPT_FILE_NAME.tmp
fi

if cmp --silent -- "$SCRIPT_FILE_NAME" "$SCRIPT_FILE_NAME.tmp"; then
  echo "No memory filelist changes detected."
else
  echo "Updating memory filelist".
  cp $SCRIPT_FILE_NAME.tmp $SCRIPT_FILE_NAME
fi

rm $SCRIPT_FILE_NAME.tmp
