#! /bin/bash

#This script does the following:
#- It copies any .mem files referenced in the Bender manifest to the GW build tree, e.g. palette.mem.
#- It generates a tcl sub script for mem files to be included in the main vivado.tcl script.
#This script does not handle the .mem file generated by the SW build system. That's handled in a separate,
#post-synthesis build step.
#
#This script is used by the build system.

if [[ "$#" == 0  || "$1" == "-h" ]]
then
  echo "$0 <src dir> <script file>"
  exit 1
fi

SRC_DIR=$1
SCRIPT_FILE_NAME=$2

echo "#Memory files" > $SCRIPT_FILE_NAME.tmp

MEM_FILE_LIST=`bender -d $SRC_DIR script -t memory flist`
for f in $MEM_FILE_LIST
do
	cp $f .
  echo "add_files -norecurse $f" >> $SCRIPT_FILE_NAME.tmp
done

if cmp --silent -- "$SCRIPT_FILE_NAME" "$SCRIPT_FILE_NAME.tmp"; then
  echo "No memory filelist changes detected."
else
  echo "Updating memory filelist".
  cp $SCRIPT_FILE_NAME.tmp $SCRIPT_FILE_NAME
fi

rm $SCRIPT_FILE_NAME.tmp
