#! /bin/bash

#This copies a .mem file generated by the SW build system (e.g. hello_world.mem) to its proper place and name in
#the GW build tree, e.g. spram.mem.
#It also generates a tcl sub script to be included in the main vivado.tcl script.
#This script is used by the build system.

if [[ "$#" == 0  || "$1" == "-h" ]]
then
  echo "$0 <input mem file> <output mem file> <script file>"
  exit 1
fi

IN_MEM_FILE=$1
OUT_MEM_FILE=$2
SCRIPT_FILE_NAME=$3

cp $IN_MEM_FILE $OUT_MEM_FILE
echo "add_files -norecurse $OUT_MEM_FILE" > $SCRIPT_FILE_NAME
