#! /bin/bash

#This script updates the SW memory image in the FPGA bitstream file
#The .mmi file is generated by Vivado during synthesis.

if [[ "$#" < 4  || "$1" == "-h" ]]
then
  echo "$0 <mmi file> <imem file> <bitstream input file> <bitstream output file>"
  exit 1
fi

MMI_FILE=$1
IMEM_FILE=$2
BITSTREAM_IN=$3
BITSTREAM_OUT=$4

#Hack: It is assumed that this is the imem memory instance that needs updating
IMEM_PROC=boxlambda_soc_inst/imem/xpm_memory_tdpram_inst/xpm_memory_base_inst
updatemem --force --meminfo $MMI_FILE --data $IMEM_FILE --proc $IMEM_PROC --bit $BITSTREAM_IN --out $BITSTREAM_OUT
