'start
(vera :display :enable)
(vera :sprites :enable)
(vera :map 0 :width 32 :height 32 :map-type +vera-map-type-tile+)
(vera :map 1 :width 32 :height 32 :map-type +vera-map-type-tile+)
(vera :layer 0 :map 0)
(vera :layer 1 :map 1)
(vera :map 0 :entry :x 0 :y 0 :val #x0002)
(vera :map 1 :entry :x 0 :y 0 :val #x2002)

(defvar w 8)
(defvar h 8)
(defvar bpp 8)
(vera :tileset 1 :width w :height h :bpp bpp :num-tiles 8)
(vera :layer 0 :tileset 1)
(vera :layer 1 :tileset 1)
(vera :sprite 1 :init)
(vera :sprite 1 :tileset 1 :tile 2)
(vera :sprite 1 :tileset)
(vera :sprite 1 :z +vera-sprite-z-dis+)
(vera :sprite 1 :z)
(vera :sprite 1 :pal-offset 1)
(dotimes (yy h)
  (dotimes (xx (min w (1+ yy)))
    (vera-tileset-pixel 1 2 xx yy +vera-color-cyan+)))



(vera :irqline 0)
(vera :linecapture :enable)
(loop (if (= (vera :linecapture :enabled) 0) (return)))
(print (vera :linecapture :pixel :x 0))

(vera :sprite 1 :z +vera-sprite-z-bg-l0+)
(vera :sprite 1 :z)
(vera :linecapture :enable)
(loop (if (= (vera :linecapture :enabled) 0) (return)))
(print (vera :linecapture :pixel :x 0))

(vera :layer 0 :enable)
(vera :linecapture :enable)
(loop (if (= (vera :linecapture :enabled) 0) (return)))
(print (vera :linecapture :pixel :x 0))
(vera :sprite 1 :z +vera-sprite-z-l0-l1+)
(vera :sprite 1 :z)
(vera :linecapture :enable)
(loop (if (= (vera :linecapture :enabled) 0) (return)))
(print (vera :linecapture :pixel :x 0))
(vera :layer 1 :enable)
(vera :linecapture :enable)
(loop (if (= (vera :linecapture :enabled) 0) (return)))
(print (vera :linecapture :pixel :x 0))
(vera :sprite 1 :z +vera-sprite-z-l1+)
(vera :sprite 1 :z)
(vera :linecapture :enable)
(loop (if (= (vera :linecapture :enabled) 0) (return)))
(print (vera :linecapture :pixel :x 0))

'end
