#Path to the root of the repository
TOP_DIR := ../..
TOP_MODULE := ibex_wb_core_wrapper

#Flag indicating Out-of-Context Synthesis of given component.
#The value corresponds the Bender.yml target used to select OOC specific files and defines.
OOC = ibex_wb_core

#Include common Make flags and rules
include $(TOP_DIR)/build_sys/common.mk

