# support for ASM_PICO picorv32 GNU assembler, associated with *.picoasm file extension.

set(ASM_DIALECT "_PICO")

set(CMAKE_ASM${ASM_DIALECT}_SOURCE_FILE_EXTENSIONS picoasm)

set(CMAKE_ASM${ASM_DIALECT}_COMPILE_OBJECT "<CMAKE_ASM${ASM_DIALECT}_COMPILER> <INCLUDES> <FLAGS> -o <OBJECT> <SOURCE>")
set(CMAKE_ASM${ASM_DIALECT}_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

include(CMakeASMInformation)
set(ASM_DIALECT)
